# Generated by Django 4.2.2 on 2023-06-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('developer', models.CharField(max_length=150, verbose_name='Developer')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Publication Date')),
                ('rating', models.FloatField(default=0, verbose_name='Rating')),
                ('views', models.IntegerField(default=0, verbose_name='Rating')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Games', to='GameDB.category')),
                ('tag', models.ManyToManyField(related_name='Games', to='GameDB.tags')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['rating', 'title'],
            },
        ),
    ]
