# Generated by Django 4.2.2 on 2023-06-07 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='GameDB.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(related_name='Game_Tag', to='GameDB.tags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Url')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Image')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('game', models.ManyToManyField(blank=True, to='GameDB.game', verbose_name='Game')),
                ('tag', models.ManyToManyField(related_name='News_Tag', to='GameDB.tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
