# Generated by Django 4.2.2 on 2023-06-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0004_news_category_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='News_Tag', to='GameDB.tags'),
        ),
    ]
