# Generated by Django 4.2.2 on 2023-06-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0005_alter_news_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
