# Generated by Django 4.2.2 on 2023-06-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0006_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Games', to='GameDB.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(related_name='Games', to='GameDB.tags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
