# Generated by Django 4.2.2 on 2023-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0007_alter_game_category_alter_game_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Publication Date'),
        ),
    ]
