# Generated by Django 4.2.2 on 2023-06-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GameDB', '0006_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Url')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Image')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='News_Category', to='GameDB.category')),
                ('game', models.ManyToManyField(blank=True, to='GameDB.game', verbose_name='Game')),
                ('tag', models.ManyToManyField(blank=True, related_name='News_Tag', to='GameDB.tags')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
