# Generated by Django 4.2.2 on 2023-06-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=0, verbose_name='Score'),
        ),
    ]
