# Generated by Django 4.2.2 on 2023-06-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0007_alter_game_category_alter_game_created_at_and_more'),
        ('Blog', '0003_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(db_index=False, default=1, on_delete=django.db.models.deletion.PROTECT, to='GameDB.game', verbose_name='Review_Game'),
            preserve_default=False,
        ),
    ]
