# Generated by Django 4.2.2 on 2023-06-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_review_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
